engine:
  type: "in_memory"
network:
  ip: "127.0.0.1"
  port: 3223
  max_connections: 100
  max_message_size: 4096
  idle_timeout: 300
  graceful_shutdown_timeout: 5
logging:
  level: "info"
  output: "stdout"
wal:  
  flush_batch_size: 100
  flush_batch_timeout: 10
  max_segment_size: 10485760
  data_directory: "/data/kv_db/wal"
