engine:
  type: "in_memory"
network:
  ip: "127.0.0.1"
  port: 3224
  max_connections: 100
  max_message_size: 4096
  idle_timeout: 300
  graceful_shutdown_timeout: 5
logging:
  level: "info"
  output: "stdout"
wal:
  flush_batch_size: 100
  flush_batch_timeout: 10
  max_segment_size: 10485760
  data_directory: "/tmp/kv_db/wal_slave"
replication:
  role: "slave"
  master_address: "127.0.0.1"
  master_port: 3333
  slave_id: "slave1"
