name: Unit tests

on:
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.2

      - name: Run tests
        run: bash unit_tests.sh
